name: Broadcast master updates to satellites

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: broadcast master changes to satellite branches
      run: |
        git config --global user.name "Git Broadcast"
        git config --global user.email "git-broadcast@no-reply.com"
        npx git-broadcast --version
        npx git-broadcast@latest --from master --push
