name: Broadcast master updates to satellites

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: broadcast master changes to satellite branches
      run: |
        npx git-broadcast --version
        DEBUG='*' npx git-broadcast@latest --from $GITUB_REF
